# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Tomblog
tagline:          'TOMBLOG'
description:      'A hub for my research and projects.'
url:              https://tomz921.github.io
baseurl:          /

author:
  name:           'Tom Serrino'
  url:            https://twitter.com/tommyserrino

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/tomz921/tomz921.github.io
